### ISSUE TITLE
[BUG] No spot reports are issued in Version 10.2.7

### ISSUE THREAD

**Issue by Nemesis2354** [Davie3/who-taunted#46]
**WoW Client Version**
10.2.7

**Lua Error**
There is no Lua Error

**Describe the bug**
In version 10.2.7, spot messages are no longer displayed. Neither in general chat nor as a raid warning

**To Reproduce**
The error is reproducible

**Expected behavior**
Various output functions of a spot message were tested. No messages are displayed in the chat channels.

**Screenshots**
No Screenshots avariable

**Additional context**
No

**Comment by Davie3** [comment]
Hi there. Can you elaborate on what issues you are having? I am not quite certain what you mean. What are the steps to reproduce the problem?

**Comment by Nemesis2354** [comment]
Hello Davie. I no longer see spot messages displayed in the chat. Neither in solo mode in the general channel, nor in the group channel or raid channel. When I taunt a mob with my paladin with the Hand of Reckoning ability, nothing happens. Yesterday I tried to generate a raid warning while taunting in a raid. There was no warning either. You can check whether the addon works for you in the current Wow version.

**Comment by Nasabiest** [comment]
I always get the error message, which is why no more spots are displayed in the chats.

`1318x [string "*WhoPulled.xml:24_OnEvent"]:2: attempt to call global 'WhoPulled_CheckWho' (a nil value)
[string "*WhoPulled.xml:24_OnEvent"]:2: in function <[string "*WhoPulled.xml:24_OnEvent"]:1>

Locals:
self = Who_Pulled {
 0 = <userdata>
}
event = "COMBAT_LOG_EVENT_UNFILTERED"
(*temporary) = nil
(*temporary) = "attempt to call global 'WhoPulled_CheckWho' (a nil value)"
`

**Comment by Davie3** [comment]
Please try version v2.1 to see if that resolves the issue.
